### ISSUE TITLE
Lets Encrypt SSL

### ISSUE THREAD

**Issue by djcroman** [Nikeev/sesdashboard#52]
Hello,
is there a Guide to install SSL Let´s Encrypt Certicate?
I install Sesdashboard over AWS.

Thank you
Dany

**Comment by Nikeev** [comment]
Hello!

Unfortunately, there is no Let´s Encrypt SSL install guide for SesDashboard. But you could use third party guides for common nginx with docker installation. I found this one: https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71 I didn't try it myself, but it looks fine to me.

In the future I'm planning to improve installation and add ssl support, but there is no estimation time for that.

Thanks.

**Comment by MaximilianKohler** [comment]
It would be easier with Caddy _(vs Let´s Encrypt)_. Here's an example: https://github.com/samyogdhital/listmonk-caddy-reverse-proxy - you just add some lines to the `docker-compose.yml` and then edit the simple caddy file.

The easiest might be to just copy jgimenez's traefik config.

**Comment by MaximilianKohler** [comment]
@jgimenez Based on that config, you have no external/global version of nginx running right? I'm installing this on an nginx vhost so I get `Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use` when I use your config. So I changed the ports like this:

```
    webserver:
      restart: unless-stopped
      image: nginx:alpine
      container_name: sesdashboard-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "82:80"
```
```
    traefik:
      image: traefik:2.9
      restart: unless-stopped
      ports:
        - "8443:443"
      command:
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.websecure.address=:443"
```
Along with a basic proxy pass to port 82 in the vhost nginx config:
```
server {
	    listen              443 ssl;
		server_name			sesdashboard.example.com; 

  location / {
        proxy_pass  http://127.0.0.1:82;
     proxy_set_header   Host            $http_host;
     proxy_set_header   X-Real-IP       $remote_addr;
     proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;  
    }

}

server {
    listen              80;
	server_name			sesdashboard.example.com; 
	  location / {
return 301 https://$host$request_uri;
	  }
}
```
Does that seem correct?

It's resulting in a "file not found" error https://github.com/Nikeev/sesdashboard/issues/68#issuecomment-2024271944.

If I change "82:80" to just "80" or "82", like you have it, I get a 502 error instead. I've tried disabling my firewall to no avail.

Changing `--entrypoints.websecure.address=:443` to 8443 makes no difference.
