### ISSUE TITLE
Docker install on nginx vhost that already has nginx, mariadb, and php running

### ISSUE THREAD

**Issue by MaximilianKohler** [Nikeev/sesdashboard#68]
**EDIT:** dev says:

>You need to either set up a completely local environment or use the docker option.

---

I'm a total noob, but I have some experience running [listmonk](https://github.com/knadh/listmonk/) with and without docker. Looking at the installation instructions https://sesdashboard.readthedocs.io/en/latest/install.html#docker-installation, the docker install downloads the contents of the .zip file https://github.com/Nikeev/sesdashboard/releases. In that folder there's a `docker-compose.yml`, which I assume is what `make init` will read from. 

Looking at the `docker-compose.yml` I expect it to not work properly. It looks like it's set up to install its own version of nginx and mysql, and even php? So I'm guessing that's going to conflict with my system which already has each of those installed. 

```
###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      restart: unless-stopped
      env_file:
        - ./.env.local
      image: mysql:8.0
      container_name: sesdashboard-mysql
      working_dir: /application
      volumes:
        - .:/application
        - sesdashboard-mysql-datavolume:/var/lib/mysql
#      ports:
#        - "8085:3306"

    webserver:
      restart: unless-stopped
      image: nginx:alpine
      container_name: sesdashboard-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      restart: unless-stopped
      build: phpdocker/php-fpm
      container_name: sesdashboard-php-fpm
      working_dir: /application
      volumes:
        - '.:/application'
        - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
volumes:
  sesdashboard-mysql-datavolume:
    driver: local
```

For comparison, here are the nginx and docker configs that get listmonk working on an nginx vhost https://github.com/knadh/listmonk/issues/1590#issuecomment-1812399067.

Am I correct that it's not possible to install sesdash on my system with docker? Or is there another `docker-compose.yml` file I could use? If not, maybe running it via Docker Desktop on my PC could work?
